const econquestions = [
    "[13.9 (c)] Suppose the waiting time is the same for all passengers. Is the cost of redeeming free tickets necessarily the same for all passengers? (3m)",
    "[14.1 (a)] Analyse whether Serine’s opportunity cost of choosing to work as an administrative officer will <b>necessarily</b> remain unchanged if the government reduces the starting salary of administrative officers. (2m)",
    "[18.1] Although air ticket fares and hotel rates are usually higher during holiday periods, many people still travel abroad. <br>Explain, in terms of opportunity cost, why it is <b>not necessarily</b> more expensive for travellers to travel abroad during holiday periods than non-holiday periods. (3m)",
    "[14.1 (b)] Analyse whether Serine’s opportunity cost of choosing to work as an administrative officer (first preference) will <b>necessarily</b> remain unchanged if the government provides unemployment benefits for all graduates seeking jobs (third preference). (3m)",
    "[SP.1] Explain whether _____ is a free good? (3m)",
    "[PP.1] Explain why _____ could be regarded as “interest”? (4m)",
    "[13.2 (a)] What are private property rights? Explain why private property rights may be weakened under this policy. (4m)",
    "[19.2 (a)] Explain whether this statement is a positive statement. (2m)",
    "[14.9 (c)] “As the amount of tax imposed on each bottle is the same irrespective of bottle size, the proportion of the larger-bottle soft drinks sold in the market will increase.” <br>Explain the argument using the law of demand. (5m)",
    "[PP.12 (a)(i)] 600 000 tickets were sold at $10 each. Tickets were sold out within a short period of time. Many citizens complained they could not purchase any tickets. <br>Illustrate the above phenomenon in a demand-supply diagram. (3m) <br><br>[PP.12 (a)(ii)] Suggest <b>TWO</b> measures which would help relieve the above problem. Illustrate your answer in <b>TWO</b> separate diagrams. (6m)",
    "[12.12 (c)(i)] The government has decided to re-introduce the Home Ownership Scheme in which eligible citizens can purchase a living unit under the scheme at a great discount. <br>With the aid of a demand-supply diagram, explain how the re-introduction of the Home Ownership Scheme would cool down the private housing market. (5m)",
    "[14.10 (e)] <b>WITHOUT</b> using a diagram, explain why the stock price of Goodbaby International (Hong Kong stock code: 1086) increased after the Chinese government considered relaxing the one-child policy in an effort to boost the birth rate. (4m)",
    "[15.11 (d)] In addition to the rise in tobacco duty, the Customs has cracked down on several illegal sellers recently. Is it possible that the quantity transacted of duty-not paid cigarettes would increase? With the aid of a diagram, explain your answer. (7m)",
    "[13.9 (a)] With the aid of a diagram, explain under what condition the total expenditure of passengers on the MTR will <b>increase</b>/*(decrease)* because of the <b>rise</b>/*(fall)* in fare. (5m)",
    "[18.5 (a)] An economist stated, “Even if the government sharply increases the wage rates of the medical staff, it is still difficult to relieve the problem.” <br>Justify his statement using the concept of elasticity of supply/demand. (3m)",
    "[13.10 (c)] The government has introduced an effective minimum wage. Subsequently, many restaurant owners claim that they are unable to employ enough workers for their restaurants at the minimum wage. With the aid of a demand-supply diagram, explain why the above phenomenon may arise. (9m)",
    "[12.5 (a)] Country A has imposed an effective price ceiling on Good X. Suppose Country A eliminates all illegal transactions of Good X. Can this price control ensure all lower income buyers obtain the quantity of Good X they plan to purchase? Explain. (4m)",
    "[16.9] Event 1: The European Union abolished the effective quota on the production of dairy products. <br>Event 2: Russia imposed an embargo on the import of dairy products from the European Union. <br>Use <b>ONE</b> demand-supply diagram to illustrate the effects of the above two events of the price of dairy products of the European Union. (4m)",
    "[14.9 (a)] Under what conditions will the buyers bear a <b>greater</b>/*(smaller)* tax burden than the sellers? Illustrate your answer with a supply-demand diagram (5m) (7m in more recent years)",
    "[17.11 (a)] Under what conditions would the buyers enjoy a <b>larger</b>/*(smaller)* share of subsidy benefit than the sellers? Illustrate your answer with the aid of a supply-demand diagram. (7m)",
    "[12.12 (b)] State <b>TWO</b> advantages and <b>TWO</b> disadvantages of being a private limited company instead of a listed company. (4m)",
    "[14.10 (d)] Explain the differences between <b>partnership</b>/*(private limited company)/(sole proprietorship)* and <b>public limited company</b>/*(private limited company)/(sole proprietorship)* in terms of <br>(i) transfer of ownership (2m) <br>(ii) legal status (2m) /*(sources of capital)/(set-up procedures)/(liability)/(continuity)/(tax rates)*",
    "[19.3] Give <b>ONE</b> example of a public corporation in Hong Kong. With reference to your example, state <b>TWO</b> advantages of providing the service by a public corporation instead of a private enterprise. (3m)",
    "[12.10 (a)(i)] Explain with <b>TWO</b> reasons why bonds could be a <b>better</b>/*(worse)* choice than shares. (4m)",
    "[16.2 (b)] From the viewpoint of owners, explain <b>ONE</b> advantage and <b>ONE</b> disadvantage of issuing shares over bonds. (4m)",
    "[PP.11 (b)] Explain whether the knowledge in textbooks is a public good. (3m)",
    "[15.2 (a)] To which type of production do <b>electronic product retailers</b>/*(farmers)/(toy factories)* belong to? Explain your answer. (2m)",
    "[PP.11 (a)] The production of textbooks involves various experts, including authors, editors, graphic designers, etc. What economic principle is illustrated? Give <b>THREE</b> reasons to explain why this principle can raise labour productivity. (4m)",
    "[18.13 (b)] Analyse how each of the following measures affects average labour productivity. (5m) <br>(i) providing subsidy for firms to improve production technology <br>(ii) importing more workers",
    "[15.10 (c)] A lot of professional football players can only find low-paid jobs after retirement. Explain the above phenomenon in terms of labour mobility. (3m)",
    "[17.12 (a)] Low-skilled European Union workers are required to apply for a visa to work in Britain after Brexit. Explain how labour mobility of the low-skilled workers from the European Union would be affected. (3m)",
    "[19.9 (c)] From the viewpoint of the <b>employer</b>/*(employee)*, suggest <b>ONE</b> advantage and <b>ONE</b> disadvantage of paying by <b>time rate</b>/*(piece rate)/(tips)/(profit sharing scheme)*. (2m)",
    "[14.2 (a)] To what factor of production does a <b>mobile phone accessory seller in Mong Kok</b>/*(sunshine)/(sewing machine)/(waiter)* belong to? Explain your answer. (2m)",
    "[16.3] State the law of diminishing marginal returns and explain whether the above data illustrates the law. (6m, if yes) (5m, if no [12.2])",
    "[14.2 (b)] Give <b>ONE</b> example of a <b>variable cost</b>/*(fixed cost)* incurred in a mobile phone accessories selling business. Explain your answer. (2m)",
    "[17.2 (b)] Due to the opening of several new branches, the average cost of production of the restaurant has <b>increased</b>/*(decreased)*. Explain with <b>TWO</b> reasons why this happened. (4m)",
    "[18.3] Explain <b>TWO</b> external <b>economies</b>/*(diseconomies)* of scale high technology firms may enjoy in Shenzhen. (4m)",
    "[19.9 (b)] Apart from Japanese cosmetic products, she starts to sell Korean cosmetic products on her website. To what expansion *(list all possible expansions)* does this belong? Give <b>TWO</b> possible reasons for this type of expansion. (3m)",
    "[17.3] Bank of China (HK) 21%, HSBC 19%, Hang Seng Bank 18%... What was the market structure of the above market *(list all possible market structures)*? List <b>TWO</b> features of this market structure. (3m)",
    "[18.12 (a)] Give <b>TWO</b> reasons to explain why the market structure of Hong Kong’s hotel industry is not perfectly competitive. (4m)",
    "[SP.9 (c)] The marginal cost at 600 units of output was $80 before the technological improvement while the marginal cost after the technological improvement is now $70 at 600 units of output. <br>(ii) Suppose the market price of electronic watches was $80 before the technological improvement. What is the output of the firm at this market price? (1m) <br>(iii) Suppose the market price of electronic watches fell to $70 after the technological improvement. What is the output of the firm at this market price? (1m)",
    "[SP.9 (b)] Suppose there is an improvement in technology that lowers the marginal cost of producing electronic watches. How would the technological improvement affect the price, quantity transacted, consumer surplus and producer surplus? (5m)",
    "[PP.4 (a)] What is “deadweight loss”? (2m)",
    "[15.4 (a)] The strong preference for small flats has pushed the prices of the flats under 400 square feet to a new high in the past few months. It is expected that more and more small flats will be available for sale in the coming future. <br>Explain <b>ONE<b> function of price which can be found in the above news extract. (2m)",
    "[PP.12 (b)(ii)] “The government should raise the ticket price so as to kick out touts.” Evaluate this proposal. (4m)",
    "[15.3] An increase in an effective quota in the market of a good would lead to a reduction in deadweight loss. Do you agree? Explain your answer with the aid of a diagram. (6m)",
    "[19.11 (b)] During non-holidays, there are a lot of empty seats on some trains of the High Speed Rail. With the aid of a figure, explain why the above situation may be inefficient. (4m)",
    "[16.4] These years many customers like to take photos of the food they have in restaurants and share them on social media. However, some high-end restaurants do not allow their customers to take photos. Explain how the “photo-taking-and-sharing” behaviour of the customers may involve externality. (3m)",
    "[17.4 (b)] Pokémon Go is a popular game for which gamers need to move around different places with their smartphones to catch the cyber-pets. Its developer has placed hotspots in different areas where many gamers are attracted to gather. Some restaurants in remote areas found their business sharply increased as they are located near these hotspots. <br>How may such a problem of inefficiency be relieved by the market? (2m)",
    "[19.4] Getting vaccinated is an effective way to prevent infection and protect oneself from flu viruses. Using the concept of externality, explain why the government provision of subsidy on Seasonal Influenza Vaccination may improve economic efficiency. (4m)",
    "[18.4] Apart from the difference in education level, explain <b>TWO<b> factors that may lead to income inequality. (4m)",
    "[12.4] According to a report of the United Nations in 2008, the Gini coefficients of Hong Kong and Beijing were 0.53 and 0.22 respectively. <br>(a) Was the income gap between the rich and the poor in Hong Kong wider or narrower than that in Beijing? (1m) <br>(b) Explain how an increase in the standard tax rate of salaries tax will affect the post-tax Gini coefficient of Hong Kong. (3m)",
    "[PP.11 (d)] Under the School Textbook Assistance Scheme (STAS), needy students are granted subsidies to cover the costs of textbooks and miscellaneous school-related expenses. <br>Explain how STAS can enhance equity in Hong Kong society. (4m)",
    "[12.10 (b)] In 2011, the Financial Secretary announced the “Scheme $6000” which provides $6000 to each Hong Kong permanent resident who is 18 years old or above. <br>Do you think that the government should introduce the “Scheme $6000” to improve equity in Hong Kong society? Explain. (4m)",
    "[15.8] The government is considering spending a certain sum of its budget surplus on the following two proposals: <br>Proposal 1: To extend free education to 15 years <br>Proposal 2: To provide unemployment benefits <br>Evaluate the two proposals in terms of equality. (4m) <br>",
    "[PP.5] Mr. Richardson, a British civil engineer, has worked for a large Hong Kong construction company for the past few years and remits his income to his family in Britain. Is his income counted in Hong Kong’s gross domestic product (GDP)? Explain your answer. (3m)",
    "[15.9 (d)] Explain whether the value of destroyed products would be included in the calculation of Hong Kong’s gross domestic product. (2m)",
    "[15.10 (a)] Suppose a football club in Hong Kong hired a famous football player from Brazil as the coach for a 2-month course for kids. He received $8 million as his salary and returned to Brazil afterwards. However, the enrollment of the course was poor and the revenue from the course was $3 million only. What is the effect of organising the above course on each of the following items? Explain. <br>(i) Hong Kong’s gross domestic product (GDP) (2m) <br>(ii) Hong Kong’s gross national product (GNP) (3m)",
    "[16.11 (a)] When a public clinic charges $45 for medical services for a patient, a price much lower than that charged by private doctors, the resulting rise in gross domestic product will be $45. Do you agree? Explain. (3m)",
    "[14.11 (b)] Suppose the sales revenue to automobile exporters was 100 billion dollars in 2013. Give <b>TWO</b> reasons to explain why their contribution to GDP would be less than 100 billion dollars in 2013. (4m)",
    "{08.11 (d)} Suppose a country’s export value of goods and services decreases by $3 billion. In reality, the resulting decrease in GDP may be less than or more than $3 billion. <br>(i) Explain a factor that would lead to a GDP decrease of less than $3 billion (3m) <br>(ii) Explain a factor that would lead to a GDP decrease of more than $3 billion (2m)",
    "[14.5 (b)] Explain <b>ONE</b> difference between using CPI and Gross Domestic Product (GDP) deflator to measure the change in the price level.",
    "{09.7 (b)} Explain with <b>TWO</b> reasons why a change in per capita real GDP cannot accurately reflect the change in the general living standard. (4m)",
    "[12.11 (a)] What is inflation? (2m)",
    "[12.11 (b)] Many workers have their salaries increased during inflation. Explain whether the real income of these workers would necessarily rise. (3m)",
    "[13.3 (a)] What is the relationship between nominal interest rate and real interest rate? (2m)",
    "[13.3 (b)] “When there is actual deflation, the nominal interest rate will be lower than the real interest rate.” Do you agree? Explain. (3m)",
    "[14.5 (c)] Suppose people did not expect any changes in the price level from 2012 to 2013. Explain whether each of the following persons would gain or lose when there is inflation. <br>(i) In 2012, Kitman borrowed a housing mortgage loan from a bank at a fixed nominal interest rate. (2m) <br>(ii) In 2012, Marlene invested in a project with an expected nominal rate of return of 12% per year. In 2013, she discovered the actual nominal rate of return was 15% per year. (3m)",
    "[12.6 (a)] State <b>TWO</b> losses to <b>society</b>/*(state other losses as well)* caused by unemployment. (2m)",
    "[15.5] Macau has developed rapidly in recent years and some workers in Hong Kong have been attracted to work there. Suppose the number of job positions in Hong Kong is constant. What would be the effect of the above phenomenon on the unemployment rate of Hong Kong? Explain your answer. (4m)",
    "[PP.7] Identify the phase which point A is in, where point A is the lowest point of real GDP growth rate. Give <b>THREE</b>/*(all)* general economic phenomena which occur in <b>this phase</b>/*(all phases)*. (4m)",
    "[13.4 (a)] Give <b>ONE</b> reason to explain why the aggregate demand curve is downward sloping. (3m)",
    "[16.5] Explain, with <b>ONE</b> reason, why the <b>short-run</b>/*(long-run)* aggregate supply curve is <b>upward-sloping</b>/*(vertical)*. (3m)",
    "[12.10 (c)] With the aid of a diagram, explain how the “Scheme $6000” would affect the price and output levels of Hong Kong in the long run. (8m)",
    "[17.12 (b)] As new visa requirements for European Union workers are imposed in Britain, discuss the effect of Brexit on aggregate output of Britain in the short run with the aid of a diagram. (2m)",
    "[15.12 (c)] <b>WITHOUT</b> using a diagram, explain how market forces can lower the output level to Yf in the long run. (4m)",
    "[13.4 (b)] Suppose aggregate output in the short run and long run are equal. After an increase in the price of raw materials, with reference to the market adjustment mechanism from the short run equilibrium to the long run equilibrium, explain the long run effect of the above change on the price level with the aid of a diagram. (9m)",
    "[14.6 (a)] Would Karen’s salary earned in Shanghai be taxed in Hong Kong? Explain your answer. (2m)",
    "[14.6 (b)] Is the salaries tax a direct or indirect tax? Explain your answer. (2m)",
    "[18.6 (b)] The tax system is turned into a progressive one. Evaluate the above changes in the tax system in terms of <b>ONE</b>/*(all)* principle of taxation put forward by Adam Smith. (2m)",
    "[14.10 (a)] With reference to a declining birth rate and an rising old-age dependency ratio, discuss the possible changes on <br>(i) government tax revenue in the future (2m) <br>(ii) public health and welfare expenditure in the future (2m)",
    "[18.6 (a)] Would turning a proportional taxation system of 16.5% into a progressive one of first 8.25% then 16.5% necessarily result in a drop in <b>profits</b>/*(income)* tax revenue? Explain. (4m)",
    "[17.6 (a)] Why can the introduction of a general sales tax stabilise government revenue in times of economic downturn? (2m)",
    "[15.11 (b)] An accountant commented that the tax base of Hong Kong is narrow and suggested that the government should introduce new types of indirect tax. Explain, with <b>ONE</b> example, how the introduction of a new indirect tax would broaden the tax base. (2m)",
    "[18.13 (a)(ii)] As the population grows older and the working-age population shrinks, discuss the possible effects of this change on fiscal balance. (3m)",
    "[SP.7 (b)] “Expansionary fiscal policy will have no effect on real income in the long run.” <br>Do you agree? Does your answer depend on how the government spends money? Explain. (6m)",
    "[13.8] Suppose a government is facing a budget deficit. Some politicians have proposed that the government should raise the income tax rate to reduce the budget deficit. Evaluate their proposal. (4m)",
    "[16.12 (c)] The recent decline in the gambling industry of Macau resulted in a drop in tax revenue for the Macanese government. Hence, the government considers reducing its spending on investment but still keeping a cash-sharing scheme. However, an economist suggests that the government should suspend the cash-sharing scheme and allocate the sum of money to investment instead. <br>Discuss the suggestion of the economist by giving arguments <b>FOR</b> and <b>AGAINST</b> it. (5m)",
    "[12.7] “9999 gold is preferred to cigarettes when used as money” Give <b>TWO</b> reasons/*(compare all properties of both)* to explain this argument. (4m)",
    "[17.5] The currency of a country depreciates sharply and becomes highly volatile. Which <b>TWO</b> functions of money may be weakened? (4m) *(Explain which <b>TWO</b> functions of money _____ can perform?)*",
    "{00.5} What is the problem of exchange in a barter economy? (1m)",
    "[16.8 (c)(i)] Why is money supply often a few times more than the monetary base? (3m)",
    "[16.8 (c)(ii)] Under what condition will money supply be equal to monetary base? (1m)",
    "{10.11 (b)(ii)} Explain briefly the process of deposit <b>contraction</b>/*(creation)* resulting from <b>increasing</b>/*(decreasing)* the required reserve ratio. (4m)",
    "[SP.6 (b)] Explain why the nominal interest rate is the cost of holding money. (3m)",
    "[14.12 (c)] What would be the short run effects of the purchase of government bonds by the central bank on the output and price levels of the economy? Explain your answer with the aid of an aggregate-supply-aggregate-demand diagram. (8m)",
    "[14.7 (b)] To reduce a growing fiscal deficit, the government can either adopt expansionary monetary policies or contractionary fiscal policies. Briefly discuss <b>ONE</b> advantage and <b>ONE</b> disadvantage of adopting an expansionary monetary policy as opposed to the contractionary fiscal policy. (4m)",
    "[18.7 (b)] Based on the quantity theory of money, predict the effect of an <b>open market purchase</b>/*(sale)* of government bonds by the central bank on the price level *(both in the short-run and long-run)*. State the assumption(s) needed to reach your conclusion. (4m)",
    "[19.8 (a)(i)] The amount of resources in Country A is twice that of Country B. Both countries allocate half their resources to produce cars and the other half to produce toys. <br>Country A: 100 cars & 100 toys. <br>Country B: 100 cars & 60 toys. <br>Explain whether Country B has an absolute advantage in producing cars. (2m)",
    "[17.7 (a)(i)] Country A and Country B both allocate half of their resources in producing food and half in producing computers. Explain whether Country B enjoys an absolute advantage in producing computers. (2m)",
    "[19.8 (a)(ii)] The amount of resources in Country A is twice that of Country B. Both countries allocate half their resources to produce cars and the other half to produce toys. Country A: 100 cars & 100 toys. Country B: 100 cars & 60 toys. <br>Explain whether Country B has a comparative advantage in producing cars. (3m)",
    "[18.8 (b)] State the principle of comparative advantage. According to this principle, explain which country should export toys. (3m)",
    "[21.9 (b)] A small open economy imports junk food from other countries although such food is also produced by local manufacturers. With respect to the imposition of an effective quota during economic recession, indicate the amount of quota as QA and the final equilibrium point as EA in the figure. (4m)",
    "[14.11 (a)] 2012: 1 HKD = 10.2 JPY, 2013: 1 HKD = 12.5 JPY <br>Japan exports automobiles to Hong Kong. Suppose the price of Japanese automobiles (in terms of Yen) does not change. With the aid of Figure 2, explain why the above change in exchange rate would lead to an increase in the total export value (in terms of Yen) of Japanese automobiles to Hong Kong. (7m)",
    "[19.11 (c)] The Guangzhou-Shenzhen-Hong Kong Express Rail Link (High Speed Rail) was launched in September 2018. <br>‘A depreciation of RMB against the US dollar (USD) will result in an increase in total revenue (in terms of HKD) of High Speed Rail tickets sold in Hong Kong.’<br>With the aid of a figure, explain under what condition this statement will be correct. (8m)",
    "[13.6 (b)] Foreign exchange and reserves assets: credit $10 million. “Country A has a balance of payments surplus because there is an increase in foreign exchange reserves in that year.” Explain whether you agree with this statement. (3m)",
    "[15.12 (a)] How would the current account balance of Hong Kong be affected if the government limited the scale of the Scheme so that the number of mainland tourists from the mainland would drop? Explain your answer. (2m)",
    "[17.12 (c)] EU officials: British citizens may require a visa to visit or to work in the EU countries. Referring to the view of the EU officials, which <b>TWO</b> components of the current account in the balance of payments of Britain may be affected? Explain your answer. (4m)",
    "[18.11] In response to the increasing military threat from Country Z, the United Nations has passed a bill to embargo most of the goods exporting from Country Z. Analyse the effects of the above situation on Country Z’s balance of payment. (4m)"
  ]
var randomnumber = sessionStorage.getItem("randomnumberstorage");
var firsttimeload = sessionStorage.getItem("firsttimeloadkey");
var shiftpressed=false;
var enternextquestion= true;
var repeatquestion=sessionStorage.getItem("repeatquestionkey"); 
const question = document.getElementById("question");
const answer = document.getElementById("answer");
const userinput = document.getElementById("userinput");
const textbox = document.getElementById("textbox");

window.addEventListener("load", function(event){
    if (firsttimeload == "false") {
        question.innerHTML = econquestions[randomnumber];
        answer.innerHTML = econanswers[randomnumber];
        textbox.style.display = "block";
        userinput.style.display = "none";
        answer.style.display = "none";
        textbox.value = "";
    } else{
        randomquestion();
    }
})

textbox.addEventListener("keydown", function(event){
        if (event.code === "Enter" && shiftpressed === false) {
            giveanswer();
            setTimeout(() => {
                enternextquestion = false
            }, 100);
        }
        if (event.code === "ShiftLeft"|| event.code === "ShiftRight"){
            shiftpressed=true;
        }
    })

textbox.addEventListener("keyup", function(event){
    if (event.code === "ShiftLeft"|| event.code === "ShiftRight"){
        shiftpressed=false;
    }
})

window.addEventListener("keydown", function(event){
    if (event.code === "Enter" && enternextquestion===false && repeatquestion !== "true"){
        randomquestion();
        enternextquestion=true;
        setTimeout(() => {
            textbox.focus();
        }, 100);
    }
})

window.addEventListener("keydown", function(event){
    if (event.code === "Enter" && enternextquestion===false && repeatquestion == "true"){
    repeatquestionfunction();
    enternextquestion=true;
    setTimeout(() => {
        textbox.focus();
    }, 100);
}
})

function togglerepeatquestion() {
    sessionStorage.setItem("repeatquestionkey","true");
    window.location.href = "index.html";
}

function togglerandomquestion() {
    sessionStorage.setItem("repeatquestionkey","false");
    window.location.href = "index.html";
}

function repeatquestionfunction() {
    randomnumber = randomnumber*1+1;
    question.innerHTML = econquestions[randomnumber];
    answer.innerHTML = econanswers[randomnumber];
    textbox.style.display = "block";
    userinput.style.display = "none";
    answer.style.display = "none";
    textbox.value = "";
}

function randomquestion() {
    randomnumber = Math.floor(Math.random() * econquestions.length);
    question.innerHTML = econquestions[randomnumber];
    answer.innerHTML = econanswers[randomnumber];
    textbox.style.display = "block";
    userinput.style.display = "none";
    answer.style.display = "none";
    textbox.value = "";
}

function giveanswer() {
    answer.innerHTML = econanswers[randomnumber];
    textbox.style.display = "none";
    userinput.style.display = "inline-block";
    answer.style.display = "block";
    var textboxuserinput = textbox.value;
    userinput.innerText = textboxuserinput;
}

function choosequestion(){
    window.location.href = "questionlist.html";
}

function getquestionnumber(clickid){
    sessionStorage.setItem("randomnumberstorage",clickid);
    sessionStorage.setItem("firsttimeloadkey","false");
    window.location.href = "index.html";
}

const econanswers = [
    "[13.9 (c)] No, (1) <br>as people have <u>different alternative uses of time</u>, (1) <br>their time costs will not be the same. (1)",
    "[14.1 (a)] Yes. (1) <br>It is because the reduction in the starting salary of administrative officers would only decrease <u>the value of Serine’s chosen option without affecting her highest valued option forgone</u>. (1)",
    "[18.1] The full cost is the monetary cost and time cost (1). <br>During holidays, the time cost of travelling abroad (e.g. value of other leisure activities) <u>may be a lot lower</u> than that in non-holiday periods (e.g. income sacrificed) (1) <br>such that the <u>decrease in time cost may be larger than the increase in monetary cost</u> (1) <br>as in the air ticket fares and hotel expenses). When the full cost is considered, travelling abroad during holiday periods may be less expensive.",
    "[14.1 (b)] No. (1) <br>Government provision of unemployment benefits may <u>increase the value of Serine’s 3rd option to a level higher than that of the 2nd option</u>. (1) <br>So the cost of choosing to work as administrative officer may now <u>change from the value of the 2nd option</u> (i.e., to work in an accounting firm as a trainee) <u>to that of the 3rd option</u> (i.e., to continue to seek a job without taking up any job and simply enjoying the unemployment benefit). (1)",
    "[SP.1] Yes/No. (1) <br>It is because more of _____ are preferred. <br>People are willing to pay a cost for _____. <br>The provision of the statistics incurs opportunity cost/the use of scarce resources. (any 2, 1@)",
    "[PP.1] To <u>the borrower</u> Peter: _____ was <u>the price/cost he paid</u> (1) <br>for <u>the earlier availability</u> of _____. (1) <br>To <u>the lender</u> Mary: _____ was <u>the premium/compensation</u> she received (1) <br>for <u>deferring consumption</u>. (1)",
    "[13.2 (a)] Private Property rights refer to <u>the exclusive right to use</u>, (1) <br><u>the exclusive right to receive income from</u> (1) <br>and <u>the right to transfer a property</u> owned by an individual. (1) <br>The private property rights over the flat under the scheme are weakened as the flat-owners’ <u>right of selling (or transferring) their flats to non-residents is confined</u>. (1)",
    "[19.2 (a)] <u>Yes</u>, Statement A is a positive statement (1) <br>because it is <u>refutable by fact</u>.(1)",
    "[14.9 (c)] Larger-bottle soft drinks are <u>more expensive</u> than smaller-bottle soft drinks. When the same amount of tax is added to each unit (bottle), (1) <br>The <u>percentage increase in price</u> of the larger-bottle soft drinks would be less than that of the <u>percentage increase in price</u> of the smaller-bottle soft drinks. (1) <br>The <u>relative price</u> of larger-bottle soft drinks (in terms of small-bottle ones) thus drops. (1) <br>Law of demand: <u>when the price of a good increases, the quantity demanded of the good decreases</u>, vice versa, ceteris paribus. (1) <br>The law of demand then implies that people would buy more larger-bottle soft drinks <u>relative</u> to small-bottle ones, so the proportion of larger-bottle soft drinks sold in the market would increase. (1)",
    "[PP.12 (a)(i)] vertical supply curve at 600 000 (1) <br>price set below equilibrium at $10 (1) <br>excess demand/shortage (1) <br><br>[PP.12 (a)(ii)] Measure one: raise the price (1) <br>Indicate in the diagram: <br>higher price (1) <br>smaller shortage (1) <br><br>Measure two: issue more tickets/extend the exhibition period (1) <br>Indicate in the diagram: <br>supply curve shifts to the right (1) <br>smaller shortage (1)",
    "[12.12 (c)(i)] Verbal elaboration: Living units under HOS and private housing are <u>substitutes</u>. (1) <br>An increased supply of public housing (living units under HOS) would result in an increase in quantity demanded of public housing, hence <u>a drop in demand</u> for private housing. (1) <br>Price of private housing drops. (1) <br><br>Indicate in the diagram:Demand shifts to the left (1) <br>Lower price (1)",
    "[14.10 (e)] People expected the birth rate to rise (case specific), resulting in an <u>expected increase in future demand</u> for the baby products. (1) <br>So Goodbaby International was <u>expected to earn bigger profits</u> (1) <br>and to distribute <u>more dividends per share</u> to its shareholders in the future. (1) <br>The <u>expected increase in future dividends would raise the demand for the company’s shares</u> and <u>thus its stock price</u> as soon as people expect changes in the one-child policy. (1)",
    "[15.11 (d)] Verbal elaboration: Due to the HK Customs’ crack-down effort, <u>the supply of duty-not-paid cigarettes would drop</u>. (1) <br>As duty-paid cigarettes and duty-not-paid cigarettes are <u>substitutes</u>, (1) <br>tobacco duty would decrease the quantity demanded of duty-paid cigarettes and thus <u>increase the demand</u> for duty-not-paid cigarettes, (1) <br>it is possible that the total quantity of duty-not-paid cigarettes sold would increase <u>if the increase in demand has a bigger effect on the quantity transacted than the decrease in supply</u>. (1) (have to mention that price would increase too) <br><br>Indicate on the diagram: Rightward shift of the demand curve (1) <br>Leftward shift of the supply curve (1) <br>Final equilibrium with a higher quantity transacted (1)",
    "[13.9 (a)] Verbal elaboration: If the demand for MTR services is inelastic, (1) <br>the percentage increase in fare will be higher than the percentage decrease in the number of trips,  (1) <br>so the total expenditure will increase. (1) <br><br>Indicate on the diagram: correct position of gain and loss (1) <br>gain > loss (1)",
    "[18.5 (a)] Supply of medical staff may be <u>inelastic</u> (1) <br>because they <u>require special training and qualification</u>. (1) <br>Even if the government raises their wage rates sharply, the <u>percentage increase</u> in quantity supplied of medical staff would still be smaller than the <u>percentage increase</u> in their wage rates. (1)",
    "[13.10 (c)] Verbal elaboration: An effective price floor is imposed above the equilibrium price and will create a surplus of workers. (1) <br>However, If the restaurant workers change to work in other industries (for example, turn into security guards) (1) <br>the supply of workers in this industry drops, (1) <br>there may be a shortage for workers at the minimum wage rate. (1) <br><br>Indicate on the diagram: wage rate set above the original equilibrium (1) <br>surplus (1) <br>magnitude of the leftward shift of the supply curve greater than the surplus (2) <br>final shortage (1)",
    "[12.5 (a)] No, because (1) <br><br>there is excess demand/shortage. (1) <br>other competitive criteria/non-price competition, such as queuing, will emerge. (2) <br>the new competitive criteria do not necessarily depend on income. (2) (Max.: 3)",
    "[16.9] Illustrate in the diagram: Embargo effect: leftward shift of demand curve (1) <br>An original kinked supply curve S0, with the vertical segment at the quota level Q0 (1) <br>Quota-abolition effect: A new upward-sloping supply curve, overlapping the kinked one below the original quota level Q0 (1) <br>Intersection of new demand curve (D1) and new supply curve (S1) results in a reduction in P (1)",
    "[14.9 (a)] The condition is that the <u>elasticity of demand for the good is smaller than the elasticity of supply</u>. (1/2) <br><br>Indicate on the diagram: Parallel upward shift of supply curve due to the per unit tax (1) <br>Price increases and quantity drops (1/2) <br>Correct position of buyers’ tax burden and sellers’ tax burden (1) <br>Buyers’ burden > sellers’ burden (1)",
    "[17.11 (a)] Verbal elaboration: The condition is that the <u>elasticity of demand for education services is lower than the elasticity of supply</u>. (2) <br><br>Illustrate in the diagram: Parallel downward shift of supply curve due to the per unit subsidy (1) <br>Correct position of New Price (P1) (1) <br>Correct position of New Quantity (Q1) (1) <br>Correct position of producer benefit and consumer benefit (1) <br>Consumer benefit > producer benefit (1)",
    "[12.12 (b)] Advantages: More difficult to be taken over (1) <br>No need to disclose the accounting information to public (1) <br>Disadvantages: cannot issue shares to the general public to raise capital (1) <br>Difficult to transfer its ownership (1)",
    "[14.10 (d)] (i) In a partnership, any given owner cannot transfer his/her shares of ownership without the consent of other partners (1) <br>while in a public limited company, the shares are freely transferable. (1) <br><br>(ii) A partnership does not have independent legal status (1) <br>while a public limited company has an independent legal status. (1)",
    "[19.3] Examples: HK Airport Authority <br>Hong Kong Export Credit Insurance Corporation <br>any other relevant example (Any 1, 1@) <br>Advantages: easier to get information about the general public from the government for decision-making <br>can provide stable service with a lower price <br>easier to get loan with the backup of the government <br>any other relevant point (Any 2, 2@)",
    "[12.10 (a)(i)] Bonds are <u>less risky</u> than shares. He can get interest return even if the company does not make any profit that year. <br><u>Higher priority</u> of getting paid than shareholders if the company is liquidated. <br><u>Relatively higher interest returns</u> than returns from dividends from shares when the company suffers a loss. (Any 2, 2@) <br><br><u>Relatively lower interest returns</u> than returns from dividends from shares when the company earns a huge profit. <br><u>No voting rights</u> in shareholders’ meetings. (Any 2, 2@)",
    "[16.2 (b)] Advantages: No interest burden <br>No redemption obligation <br>Easier to obtain more bank loans with a lower debt-to-equity ratio (Any 1, 2@) <br><br>Disadvantages: Diluting the control over the firm as new shareholders may influence company decisions <br>Higher risk of being taken over (Any 1, 2@)",
    "[PP.11 (b)] Yes/No (1) <br>_____ is non-rival in consumption (1). <br>A person’s consumption will not reduce the amount available to others. (1) <br>OR Knowledge is non-excludable in consumption (1).  <br>It is too costly to exclude others from consuming _____ (1).",
    "[15.2 (a)] Tertiary production (1) <br>As it provides retail services. (1) <br><br>Primary production (1) <br>As they directly use natural resources like soil and sunshine to grow crops. (1) <br><br>Secondary production (1)<br>As they turn raw materials into toys, which are finished goods. (1)",
    "[PP.11 (a)] Division of labour/Specialisation (1) <br>Reasons: Practice makes perfect <br>The most suitable person is chosen for the job <br>Economy of time, time is saved in training <br>Economy of time: time is saved in job rotation <br>Capital goods are fully utilised <br>Mechanisation is stimulated (Any 3, 1@)",
    "[18.13 (b)](i) Subsidy: Labour productivity would rise (1) <br>as improved technology or higher quality of capital goods would result in an increase in output per unit labour. (1) <br><br>(ii) Importing more workers: Uncertain. (1) <br>Labour productivity would increase if (1) <br>the imported workers are more productive on average than the existing local ones. (1)",
    "[15.10 (c)] Professional football players have low (1) <br>occupational mobility, (1) <br>As their skills are very specific and not easily transferable to other jobs. (1)",
    "[17.12 (a)] The geographical mobility of low-skilled workers from the EU (1) <br>would be lowered (1) <br>because the visa requirement (case specific) would increase the cost for those EU workers to go to work in the UK. (1)",
    "[19.9 (c)] Advantage: Cost of <u>measuring output and wage payment</u> of the employees can be saved. *(higher cost as disadvantage for other payment methods)* <br>Lower cost of <u>monitoring product quality</u> *(higher cost as disadvantage for other payment methods)* (Any 1, 1@) <br>*(For profit sharing scheme: Transferring some business risks to workers)* <br>Disadvantage: <u>Work incentive</u> and average labour productivity may not be high *(High as advantage for other payment methods)* <br>Higher cost of <u>monitoring worker’s performance</u> *(Lower cost as advantage for other payment methods)* (Any 1, 1@) <br><br>Advantage: Stable income (1) *(Unstable as disadvantage for other payment methods)* <br>Disadvantage: Can not earn a higher income by working harder (1) *(Can as advantage for other payment methods)*",
    "[14.2 (a)] Entrepreneurship (1) <br>As he <u>bears business risk</u> and makes business decisions (1) <br><br>Land (1) <br>Sunshine is a <u>natural resource</u>, a <u>gift of nature</u>, used in production. (1) <br><br>Capital (1) <br>A sewing machine is a <u>man-made resource</u> used in production. (1) <br><br>Labour (1) <br>Both <u>mental and physical effort</u> provided by the waiter is involved in serving customers in a restaurant. (1)",
    "[16.3] The law states that (holding technology constant,) when <u>more units of a variable factor</u> are added successively (1) <br>to <u>a given quantity of fixed factors</u>, (1) <br>the <u>marginal products of the variable factor will eventually diminish</u>. (1) <br><br>Yes (1) <br>When labour increases <u>from 3 to 4 units</u>, (1) <br><u>the marginal product of labour drops</u> from 18 to 14 units, so the law of diminishing returns holds. (Draw a table) (1) <br><br>OR No (1) <br>Because all factors are <u>variable</u>. (1)",
    "[14.2 (b)] Cost of buying the accessories, or wages of part-time workers (1) <br>As expenses on these items would <u>vary (increase) with the output of Ah Wing’s shop</u>. (1) <br><br>Cost of paying rent for the mobile phone accessories shop. (1) <br>The cost of rent would <u>not vary (increase) with the output</u> of Ah Wing’s shop. (1)",
    "[17.2 (b)] Financial diseconomies of scale: The firm may have <u>large outstanding loans</u>, (1) <br>so the <u>marginal cost of further borrowing</u> increases, the <u>long run average cost</u> increases. (1) <br>Technical diseconomies of scale: The firm may have <u>excessive capacity</u>, (1) <br>so the <u>long run average cost</u> may increase. (1) <br>Purchasing diseconomies of scale: As <u>supply of resources are limited</u>, (1) <br>so the firm may have to use <u>costlier substitutes</u> or buy from more expensive sources, increasing <u>long run average cost</u>. (1) <br>Marketing diseconomies of scale: The market may have <u>saturated</u>, (1) <br>leading to a rise in the marketing cost and <u>long run average cost</u>. (1) <br>Managerial diseconomies of scale: The organisation of the firm may have become too <u>complicated</u>, (1) <br>so <u>managerial efficiency starts declining</u> and increasing <u>long run average cost</u>. (1) (Any 2, 2@) <br><br>Financial economies of scale: Larger firms can <u>bargain a lower borrowing rate</u>, (1) <br>so the <u>marginal cost of further borrowing</u> decreases and the <u>long run average cost</u> decreases. (1) <br>Technical economies of scale: The firm may afford <u>more advanced machines</u>, (1) <br>so <u>productivity is raised  with a lower long run average cost</u>. (1) <br>Purchasing economies of scale: Larger firms can <u>buy its inputs in bulk</u>, (1) <br>so the firm can <u>enjoy a larger discount</u>, lowering the <u>long run average cost</u>. (1) <br>Marketing economies of scale: The firm can <u>spread its advertising costs over a larger output</u>,(1) <br>lowering the <u>long run average cost</u>. (1) <br>Managerial economies of scale: Larger firms can <u>apply a wider scope of specialisation among managers</u>, (1) <br>so <u>productivity is raised with lower long run average cost</u>. (1) (Any 2, 2@)",
    "[18.3] With a larger industry, <u>more workers are attracted and trained</u>, (1) <br>so the <u>average (marginal) cost of recruiting skilled workers</u> could be reduced. (1) <br>With a larger industry, <u>publicity about the industry</u> increases when more firms advertise, (1) <br>so a single firm’s <u>cost of marketing and promotion</u> could be reduced. (1) <br>With a larger industry, <u>demand for transport services increase</u> and develops the market for corresponding services, (1) <br>so <u>transportation costs</u> could be reduced. (1) (Any 2, 2@) <br><br>With a larger industry, a <u>drastic increase in demand for inputs raises input prices</u>, (1) <br>so the <u>average cost of obtaining inputs</u> increases. (1) <br>With a larger industry, the <u>market may become saturated</u>, (1) <br>so the <u>marketing cost for a firm</u> may increase greatly. (1) <br>With a larger industry, transport services may <u>become too large and charge higher prices</u>,(1) <br>so <u>transportation costs</u> could increase. (1) (Any 2, 2@)",
    "[19.9 (b)] Horizontal expansion. (1) <br>Reasons: Enjoy economies of scale <br>Enlarge the market share <br>Make use of the brand name (Any 2, 1@) <br>(External: Better use of resources, reduce duplication of facilities, reduce competition) <br><br>Vertical expansion (1) <br>Reasons: Enjoy economies of scale <br>Secures supply of inputs (backward) <br>Secures market outlets for outputs (forward) <br>Reduce expenses in transactions <br>Extend brand name to other products <br>(External: Better use of resources)  (Any 2, 1@) <br><br>Lateral expansion (1) <br>Reasons: Enjoy economies of scale <br>Extend brand name to other products <br>Spread risk through product diversification <br>Attract customers from its competitors by offering various related products <br>(External: Better use of resources) (Any 2, 1@) <br><br>Conglomerate expansion (1) <br>Reasons: Enjoy economies of scale <br>Extend brand name to other products <br>Spread risk through product diversification <br>Invest in other more profitable industries <br>(External: Better use of resources) (Any 2, 1@)",
    "[17.3] Oligopoly. (1) <br>There are only several dominant firms. <br>There are entry barriers. <br>Market information is imperfect. <br>Firms are price searchers. <br>Pricing strategies are interdependent. (Any 2, 1@) <br><br>Monopoly. (1) <br>There is only one seller in the market. <br>There are insurmountable entry barriers/There is no entry into the market. <br>There are no close substitutes for the products or services provided by the monopolist. <br>Market information is imperfect. <br>Firms are price searchers. (Any 2, 1@) <br><br>Monopolistic competition. (1) <br>There are many sellers but no dominant sellers. <br>Heterogeneous products are sold. <br>There are no entry barriers. <br>Market information is imperfect. <br>Firms are price searchers. (Any 2, 1@) <br><br>Perfect competition. (1) <br>There are many sellers but no dominant sellers. <br>Homogeneous products are sold. <br>There are no entry barriers. <br>Market information is perfect. <br>Firms are price takers. (Any 2, 1@)",
    "[18.12 (a)] Sellers provide heterogeneous services, (1) <br>e.g., rooms with different size/features. (1) <br><br>Market information is imperfect, (1) <br>e.g., information about the quality of services. (1) <br><br>Price searcher / under competition there are different prices, (1)<br>e.g., different hotels charge different room rates for similar rooms. (1) (Any 2, 2@)",
    "[SP.9 (c)] (ii) 600 (1) <br>(iii) 600 (1)",
    "[SP.9 (b)] Supply will increase, (1) <br>resulting in a lower price, (1) <br>a larger quantity transacted, (1) <br>larger consumer surplus (1) <br>and larger producer surplus (given a parallel shift in supply). (1)",
    "[PP.4 (a)] Deadweight loss is the loss in the total social surplus or <u>the potential gains not fully captured</u> (1) <br>when <u>marginal benefit does not equal marginal cost.</u> (1)",
    "[15.4 (a)] Allocative function (1) <br>Higher prices of small-sized flats would induce real-estate developers to <u>direct more resources towards</u> the production of small flats. (1) OR <br>Signal function (1) <br>Prices help <u>transmit information</u> about consumer <u>demand relative to</u> producer <u>supply</u>. (1)",
    "[PP.12 (b)(ii)] Government: Increasing the ticket price can reduce ticket-touting as well as increase the total revenue of the exhibition. (2) <br>Society/efficiency: Less time wasted on queue lowers the efficiency loss. (2) <br>Consumers: Smaller shortage implies easier to get a ticket. (2) <br>Consumers: Higher prices will result in a lower consumer surplus. (2) <br>Touts: The resale of the ticket is less profitable so fewer people engage in ticket-touting. (2) (Any 2, 2@)",
    "[15.3] Agree. (1) <br>Verbal elaboration: <br>The increase in effective quota would raise the supply and thus raise the quantity transacted and reduce the price. (1) <br>The <u>gap between marginal benefit and marginal cost</u> is reduced as the quantity produced is <u>increased toward its effective level.</u> (1) <br><br> Indicate on the diagram: <br>Rightward shift of the supply curve corresponding to an increase in quota (1) <br>A reduction in P and a rise in Q (1) <br>Correct position for the reduction in deadweight loss (1)",
    "[19.11 (b)] Verbal elaboration: <br>Fares are set above the market-clearing (or equilibrium) level. (1) <br>So the marginal benefit of train service is larger than the marginal cost. (1) <br><br>Illustrate in the diagram: <br>correct position of P and Q (1) <br>correct position of deadweight loss (1)",
    "[16.4] Taking photos may disturb other people in the restaurants/sharing the photos in the social media may disclose the design of dishes. (1) <br>Both possibilities may have an <u>undesirable effect</u> on the revenue/profit of the restaurants, but such effects are <u>not compensated</u> (financially or otherwise) by the photo-takers. (1) <br>Such photo-taking and sharing behaviour may thus involve <u>negative externality</u> (external cost is involved). (1) OR <br>Taking photos and sharing them in social media may attract more customers – bringing higher revenue/profit – to the restaurants, <br>such photos have a desirable effect but the photo-takers <u>do not receive compensation</u> for such benefits. (1) <br>Such photo-taking and sharing behaviour may thus involve positive externality (external benefit is involved). (1)",
    "[17.4 (b)] The restaurants may pay the game developer to increase the hotspots nearby. (2) <br>OR<br>The game developer may charge the restaurants for placing more hotspots near them. (2)",
    "[19.4] Getting vaccinated protects oneself as well as lowering the chance of others being infected by the flu. (1) <br>Since the person receiving vaccination is <u>not compensated</u> by others (whose chances of being infected are reduced), (1) <br>there exists <u>external benefit</u>, as marginal social benefit exceeds marginal social cost. This implies that the number of people getting vaccinated is <u>below the efficient level</u>. (1) <br>Subsidy can increase the quantity of vaccination <u>towards the efficient level</u> and thus <u>narrow the gap between marginal social benefit and marginal social cost</u>. (1)",
    "[18.4] Race, as there may be racial discrimination in the job market and some ethnic minority groups may suffer a lower wage rate for the same job. <br>Gender, as sex discrimination may exist in the workplace. On average, females suffer a lower wage rate for the same rank. <br>Physical attributes, as average income may be higher for people who are fitter, or taller, or better-looking since these people are more productive for certain jobs (e.g. sportsmen, fashion models). (Any 2, 2@)",
    "[12.4] (a) wider (1) <br>(b) Lower, because (1) <br>higher income group has a lower post-tax income (1) <br>while the income of the lower income group remains unchanged. (1)",
    "[PP.11 (d)] The STAS increases the income of the needy students’ families while the rich families cannot enjoy this benefit. <br>The STAS will help equalise opportunities as it helps the needy students further their studies. <br>Education can help equalise income, it increases the future income of the lower income students so it may help narrow the income gap over time. (Any 2, 2@)",
    "[12.10 (b)] Equity is a subjective concept that involves value judgments. / Different people use different standards of equity. (1) <br>Yes, it <u>equalises income</u> because the $6 000 results in a higher percentage increase in income of the lower income group compared to the higher income group. (2) <br>No, as it does not help <u>equalise opportunities</u>. Relative to the rich, the poor do not get more resources to improve their productivity / increase their future income. (2) <br>No, as it is not <u>equalising outcome</u> as not everyone can benefit from the scheme, non-permanent residents and residents who are below 18 years old are not eligible for the $6 000. (2) (Any 2, 2@)",
    "[15.8] Proposal 1: Equalising opportunities (1) <br>Free education for longer years means that lower income groups are able to receive more education and improve their productivity and hence increase income-earning power in the future while it is unlikely to increase the years of education that the higher income groups receive. <br>Proposal 2: Equalising income/outcome (1) <br>More welfare payments to the unemployed could help reduce the income inequality between the employed and the unemployed, who typically belong to the lower income class. As such, the lower income group’s disposable income increases while that of the higher income group remains unchanged. (1) <br>",
    "[PP.5] Yes. (1) <br>Because it is derived from the <u>current production</u> (1) <br>by a <u>resident producing unit</u> in Hong Kong. (1)",
    "[15.9 (d)] No (1) <br>Because it is not sold to the market and thus <u>not counted as production</u>. [Output Approach] (1) <br><br>OR Because it is neither counted in consumption nor investment. [Expenditure Approach] (1)",
    "[15.10 (a)] (i) HK’s GDP would increase (by $3 million). (1) <br>As the course is a <u>current-year production by a resident production unit</u>, its value would be included in GDP. (1) <br><br>(ii) HK’s GNP would decrease (by $5 million), (1) <br>as change in <u>GNP</u> = change in GDP (+$3 million) + <u>change in net income from abroad</u> (–$8 million). (1) <br>As the Brazilian coach is <u>NOT a HK resident</u>, the $8 million he received would be counted as <u>income outflow</u> and enter as a negative item in HK’s national income account. (1)",
    "[16.11 (a)] No. (1) <br>Because the public service is not sold at the market price (1) <br>and will be counted using <u>factor cost</u> in the GDP (1)",
    "[14.11 (b)] Not all factor inputs used to produce Japanese cars originated from Japan, (1) <br>e.g. some of the parts or raw materials were imported. (1) <br>Some Japanese cars sold in 2013 were not produced in the same year, (1) <br>e.g. some of them came from inventory. (1)",
    "{08.11 (d)} (i) Part of the decrease in export value would not lead to a corresponding decrease in GDP when, referring to those $3 billion worth of exports, <br>part of it is not locally produced. (2) <br>e.g. some of the production raw materials are imported (1) <br>e.g. part of the value of these exports comes from the value of re-exports (1) (Any 1, 1@) <br>part of it is not produced in the current year. (2) <br>e.g. some of these exports are second-hand goods (1) <br>e.g. some of these exported goods come from the inventory (1) (Any 1, 1@) <br>part of those goods not exported have already been produced. (2) <br>e.g. those goods not exported are sold locally (1) <br><br>(ii) The amount of GDP derived from the spillover effect of the production of the exports will also decrease. (1) <br>Because as GDP drops, consumption also drops. (1)",
    "[14.5 (b)] CPI only includes <u>consumer goods</u> (1) <br>while GDP deflator includes <u>both consumer goods and producer goods</u>. (1) <br>CPI calculates a <u>fixed basket of goods</u> and the weighting will be <u>revised every 5 years</u> (1) <br>while GDP deflator has <u>variable baskets of goods</u> for <u>each year</u>. (1) (Any 1, 2@)",
    "{09.7 (b)} Income distribution: If income is unevenly distributed, (1) <br>the corresponding change in the living standard of ordinary people will be overestimated. (1) <br><br>Composition of output: If a large proportion of total output consists of capital goods, national defence, etc, (1) <br>the corresponding change in the general living standard will be overestimated. <br><br>Undesirable effects of production: The problems of pollution or traffic congestion would lower the living standard. (1) <br>Therefore, the corresponding change in the general living standard would be overestimated without such information. (1) <br><br>Amount of leisure: Leisure would raise the living standard. (1) <br>Therefore, the corresponding change in the general living standard would be underestimated without such information. (1) <br><br>Unreported production activities: The consumption of non-marketed goods / the existence of unreported transactions would improve the living standard. (1) <br>Therefore, the corresponding change in the general living standard would be underestimated without such information. (1) (Any 2, 2@)",
    "[12.11 (a)] A persistent increase (1) <br>in the general price level (1)",
    "[12.11 (b)] No. (1) <br>Because the real income of workers would fall if the <u>percentage increase in price level is greater</u> (1) <br>than the <u>percentage increase in nominal wage</u>. (1)",
    "[13.3 (a)] Nominal interest rate (R) = expected inflation rate + real interest rate (r) (2)",
    "[13.3 (b)] No, (1) <br>R will be lower than r only when the expected inflation rate is negative. (1) <br>But the existence of actual deflation does not imply that the deflation is expected. (1) <br><br>OR Yes, (1) because people may expect deflation beforehand (1) <br>and an expected deflation will result in a nominal interest rate being lower than real interest rate. (1) <br><br>OR Yes, (1) <br>because the realised (actual) real interest rate will be higher than the nominal interest rate (1) <br>when there is actual deflation. (1)",
    "[14.5 (c)] (i) Kitman would gain (1) <br>Because the unexpected inflation would <u>lower the real value</u> (purchasing power) of the loan payment. (1) <br><br>(ii) Marlene would lose (1) <br>Because, given the 15% rate of actual nominal return and the 5% rate of actual inflation, her <u>actual rate of return</u> equals 10% (= 15% – 5%), (1) <br>which <u>falls short of her expected real rate of return</u> (12%). (1)",
    "[12.6 (a)] Loss of output <br>Loss of human capital <br>Political unrest (Any 2, 1@) <br><br>To the unemployed: Lower living standard <br>Family problems <br>Loss of skills and working experience (Any 2, 1@) <br>To the government: Financial burden",
    "[15.5] Unemployment rate = (number of unemployed / total labour force) x 100% (1) <br>Since both total labour force and number of unemployed <u>drop by an equal amount</u>, (1) <br>the <u>percentage decrease</u> in the unemployed population is <u>greater</u> than the <u>percentage decrease</u> in the total labour force, (1) <br>implying a reduction in the unemployment rate. (1)",
    "[PP.7] Depression (Trough) (1) <br>Phenomena: Employment is at a low level. / Unemployment is at a high level. <br>Inflation is at a low level. / There may be deflation. <br>Aggregate demand is at a low level. <br>Business confidence is at a low level. <br>Low or negative real GDP growth rate. (Do not use this if this is indicated in the diagram) (Any 3, 1@) <br><br>Recovery (Expansion) (1) <br>Phenomena: Employment is increasing. / Unemployment is decreasing. <br>Inflation is rising. / Deflation is slowing. <br>Aggregate demand is increasing. <br>Business confidence is increasing. <br>Rising real GDP growth rate. (Any 3, 1@) <br><br>Peak (Prosperity/Boom) (1) <br>Phenomena: Employment is at a high level. / Unemployment is at a low level. <br>Inflation is at a high level. <br>Aggregate demand is at a high level. <br>Business confidence is at a high level. <br>Highest real GDP growth rate in the cycle. (Any 3, 1@) <br><br>Recession (Contraction) (1) <br>Phenomena: Employment is decreasing. / Unemployment is increasing. <br>Inflation is decreasing. / There may be deflation. <br>Aggregate demand is falling. <br>Business confidence is falling. <br>Decreasing or negative real GDP growth rate. (Any 3, 1@)",
    "[13.4 (a)] Wealth effect: When the price level increases, <u>real wealth</u> decreases as the same amount of money is able to buy fewer goods and services (1) <br>so <u>real consumption expenditure</u> decreases. (1) <br>Hence, <u>aggregate output demanded decreases when the price level increases</u>. (1) <br><br>Interest rate effect: When the price level increases, the purchasing power of money decreases, the transaction demand for money increases and <u>interest rate</u> increases (1) <br>so <u>real consumption and investment expenditure</u> decreases. (1) <br>Hence, <u>aggregate output demanded decreases when the price level increases</u>. (1) <br><br>Exchange rate effect: When the price level increases, as domestically produced products and foreign products are substitutes, the <u>price of domestically produced products become relatively more expensive relative foreign products</u>, (1) <br>so the volume of exports decreases while the volume of imports increases, thus the <u>real value of exports</u> decreases. (1) <br>Hence, <u>aggregate output demanded decreases when the price level increases</u>. (1) (Any 1, 3@)",
    "[16.5] <u>Imperfect adjustment of input prices</u> in the short-run, the percentage increase in the price level is higher than the percentage increase in nominal factor cost. (1) <br><u>Real cost of production</u> decreases. (1) <br>Hence, the short-run aggregate supply curve is upward-sloping as the <u>aggregate output supplied increases when the price level increases</u>. (1) <br><br><u>Perfect adjustment of input prices</u> in the long-run, the percentage increase in the price level and percentage increase in nominal factor costs are the same (1) <br>No change in <u>real production costs</u>. (1) <br>Hence, the long-run aggregate supply curve is vertical at the potential output as the <u>real output in the long-run only depends on the production capacity</u> of the economy. (1)",
    "[12.10 (c)] Disposable income increases. (1) <br>Real consumption expenditure increases. (1) <br>Aggregate demand increases. (1) <br>Price level increases. (1) <br>Aggregate output unchanged in the long run. (1) <br><br>Indicate in the diagram: AD shifts to the right (1) <br>Vertical LRAS (1) <br>P increase and Y unchanged (1)",
    "[17.12 (b)] The new visa requirement would increase labour cost for the British firm owners, (1) <br>resulting in a drop in SRAS. (1)",
    "[15.12 (c)] Hong Kong is facing an inflationary gap. (1) <br>There is an excess demand in the factor market, (1) <br>creating pressure for factor prices to adjust upward, so that costs of production would increase over time (1) <br>and short run aggregate supply (SRAS) would fall over time, restoring output to Yf in the long run. (1)",
    "[13.4 (b)] Verbal elaboration: Increase in the price of raw materials results in <u>a rise in factor prices</u>. So the <u>short run aggregate supply</u> (SRAS) will decrease. (1) <br><u>Price level</u> increases and the <u>output</u> will fall <u>in the short run</u>. (1) <br>A <u>deflationary gap</u> forms. (1) <br><u>Excess supply in the factor market</u> will result in a <u>downward pressure on the input prices</u>, so <u>costs of production would decrease over time</u>. (1) <br>In the long run, wages will adjust downward and the SRAS will increase and the price level will <u>fall back to the original level</u>. (1) <br><br>Indicate on the diagram: SRAS shifts to the left (1) <br>P increases, Y drops (1) <br>SRAS shifts back to the original position (1) <br>final fall in P, back to original level (1)",
    "[14.6 (a)] No, (1) <br>because according to the source principle, income not derived from Hong Kong would not be taxed by the HK government. (1)",
    "[14.6 (b)] Direct tax (1) <br>because the tax burden cannot be shifted by these tax-payers to someone else. (1) <br>Indirect tax (1) <br>because the tax burden can be shifted by these tax-payers to someone else. (1)",
    "[18.6 (b)] Equality: (1) <br>The new tax is <u>no longer proportional</u>, meaning that it is inconsistent with the equality principle. <br>Economy: (1) <br>The new tax system may incur a <u>slightly higher administration cost</u>, rendering it less in line with the economy principle. (1) <br>Certainty: (1) <br>Both the new and old tax systems are equally <u>well-defined and announced publicly</u>, so the new one would be just as certain as the old. (1) <br>Convenience: (1) <br>There is no change in the method of tax collection, so the change in tax system <u>would not impose any extra cost</u> on taxpayers and hence will have no effect on convenience. (1) (Any 1, 2@)",
    "[14.10 (a)] (i) A declining birth rate implies a <u>slower growth in the size of the work force</u> and possibly a <u>shrinking working population</u> in the future. (1) <br>As <u>fewer workers</u> are there to pay taxes, future tax revenue may be reduced. (1) <br><br>(ii) A rising old-age dependency ratio implies a <u>higher percentage of the elderly</u> in the population. The elderly may have <u>lower (or even zero) income </u>and <u>greater needs for medical services</u>. (1) <br>They may thus require <u>more government support</u> in terms of social welfare and public health, implying an increase in public expenditure on such programs. (1)",
    "[18.6 (a)] No. (1) <br>The reduction in the profits-tax rate may <u>induce firms to increase their investment expenditure</u> due to the incentive effect, (1) <br>so they may end up earning <u>higher profits</u> (tax base). (1) <br>The increase in profits tax revenue due to the increase in profits (tax base) may be greater than the decrease in profits tax revenue due to the reduction in tax rate. (1) <br><br>No. (1) <br>The reduction in the income tax rate may <u>induce workers to work longer hours</u> due to the incentive effect, (1) <br>So they may end up earning <u>higher wages</u> (tax base). (1) <br>The increase in income tax revenue due to the increase in income (tax base) may be greater than the decrease in income tax revenue due to the reduction in tax rate. (1)",
    "[17.6 (a)] As <u>fluctuation</u> in consumption is smaller than that of income. (1) <br>Sales-tax revenue generated from consumption would <u>fall less relatively</u> when compared to income-tax revenue generated from income, thus <u>stabilising total government revenue</u>, during an economic downturn. (1) <br>OR Introduction of a general sales tax </u>broadens the tax base<u>, (1) <br>so that the tax revenue collected would <u>fluctuate less</u>. (1)",
    "[15.11 (b)] Introduction of new types of indirect taxes, such as general sales tax or value-added tax, (1) <br>would make more people or commodities fall into the tax brackets, thus broadening the tax base. (1)",
    "[18.13 (a)(ii)] The fiscal balance may be worsened. (1) <br><u>Government revenue may drop</u>, as the working-age population, which accounts for a major portion of taxpayers, drops. (1) <br><u>Government expenditure may increase</u>, as the government spends more on medical services and transfer payments to the growing old-age population. (1)",
    "[SP.7 (b)] An increase in government consumption expenditure will <u>increase the aggregate demand</u>, leading to an increase in real income in the short run. (1) <br>But in the long run, <u>real income will not be affected</u> (1) <br>because the <u>long run aggregate supply curve is vertical</u> at the potential income level. (1) <br>However, if the government spends its money on <u>investment</u>, (1) <br>the accumulation of capital may <u>raise potential income</u>. (1) <br>In this case, an expansionary fiscal policy <u>may increase real income</u> in the long run. (1)",
    "[13.8] Government should increase the income tax rate to reduce the budget deficit: if the increase in tax revenue due to the rise in tax rate <u>outweighs</u> the reduction in tax payment due to the reduction in the tax base/taxable income (e.g., a fall in the number of taxpayers as a result of disincentive effects to labour). (4) <br>because increase in tax rate is fairer as income tax is often proportional (or even progressive) and this helps equalise income. (2) <br>if there is an inflationary (output) gap as an increase in income tax reduces output and relieves the inflationary pressure. (2) <br><br>Government should not increase the income tax rate to reduce the budget deficit: if the increase in tax revenue due to the rise in tax rate <u>falls short</u> of the reduction in tax payment due to the reduction in the tax base/taxable income (e.g, a fall in taxable income as a result of reduction in aggregate output). (4) <br>because an increase in income tax rate will result in a greater disincentive to work and more people may quit the job and rely on welfare programmes and this further worsen the budget deficit. (2) <br>as an increase in income tax rate reduces the aggregate output, which may result in unemployment/deflationary (income) gap. (2) <br>any other relevant point (max. 4)",
    "[16.12 (c)] Arguments for: Investment would <u>increase the potential output</u> over time through the accumulation of capital, (1) <br>but cash sharing <u>would not have similar long-run effects on the economy</u> as it would only increase aggregate demand through raising disposable income and consumption. (1) <br>Investment would <u>raise aggregate demand directly</u>. (1) <br>But the cash-sharing scheme could only raise aggregate demand indirectly via an increase in consumption through raising disposable income. If the residents <u>choose not to spend the cash received</u> on consumption, <u>the increase in aggregate demand would be diminished</u>. (1) <br>Any other relevant point. (2@, max. 3) <br><br>Arguments against: <br>During an economic downturn, a reduction in social welfare due to suspension of the cash-sharing scheme may result in <u>discontentment of the citizens and political instability</u>. (2) <br>While people can benefit from the cash-sharing scheme <u>instantly</u>, (1) <br>it may take a <u>longer time</u> for investment to boost their income. (1) <br>Public investment may be <u>inefficient</u> due to <u>high administrative costs</u> or <u>low sensitivity to market/price signals</u> (lack of profit incentives). (2) <br>Any other relevant point. (2@, max. 3) <br>Remarks: Maximum marks for part (c) is 5 marks",
    "[12.7] Gold is more durable (1) <br>while cigarettes may <u>lose their value during transactions</u>. (1) <br>Gold is more generally accepted as a medium of exchange (1) <br>while cigarettes are <u>not generally accepted as a medium of exchange</u>. <br>Gold is more homogenous (1) <br>while cigarettes may <u>differ in quality</u>. (1) (Any 2, 2@) <br><br>A is more limited in supply (1) <br>while the supply of B may be <u>increased easily such that the value of each unit of B may drop significantly</u>. People may be reluctant to accept it in exchange and store it for future purchases. (1) <br>A is more stable in value (1) <br>while the value of B may fluctuate greatly. People may be reluctant to accept it in exchange and store it for future purchases. (1) <br>A is divisible (1) <br>while B can not be <u>divided to settle payments of different amounts</u>. This <u>increases the cost of transactions</u>. (1) <br>A is more portable (1) <br>while B has a <u>higher cost in transporting it</u> to carry out transactions. (1) <br>A has denominations printed on it (1) <br>while B does not have a <u>face value</u> indicated on it, which may lead to disputes about its value during transactions.",
    "[17.5] Store of value. (1) <br>As the value of the local currency drops in terms of foreign currency, its <u>purchasing power in terms of the quantity of foreign goods and services would also fall</u>. <br>Standard of deferred payment. (1) <br>As the value of the currency becomes highly volatile, the <u>contracting cost</u> of <u>specifying future payments in terms of this currency</u> would increase. (1) <br>Medium of exchange. (1) <br>Some multinational firms may refuse to accept the currency if its value fluctuates too much, <u>weakening the currency’s ability to facilitate the buying and selling of goods and services</u>. (Any 2, 2@) <br><br>Unit of account: (1) <br>The price of (the good/service in question) is expressed in terms of _____. (1)",
    "{00.5} The problem of exchange is the need to search for <u>double coincidence of wants</u>/the act of buying and the act of selling cannot be separated. (1)",
    "[16.8 (c)(i)] A <u>fractional reserves banking system</u> (1) <br>enables the banks to <u>lend out money and create loans</u>, (1) <br>which eventually will be <u>redeposited back</u> into the banks as deposits, resulting in a multiple increase in deposits / the banking multiplier is larger than unity. (1)",
    "[16.8 (c)(ii)] If the <u>legal reserve ratio is 100%</u> or <u>all banks do not lend out their excess reserves</u>, money supply will be equal to the monetary base. (1)",
    "{10.11 (b)(ii)} An increase in the reserve ratio (1) <br>Insufficient required reserves (1) <br>Banks have to call back loans (1) <br>Withdrawals of deposits from borrowers to repay loans which cause a further withdrawal of deposits from the banking system (1) <br>The process will go on and on until the actual reserve is equal to the required reserve. (1) <br><br>An decrease in the reserve ratio (1) <br>Excess reserves (1) <br>Banks do not keep excess reserves and loans them out (1) <br>The public redeposits the loans into the banking system and deposits increase further (1) <br>The process will go on and on until the actual reserve is equal to the required reserve. (1)",
    "[SP.6 (b)] The nominal interest rate is the return to holding interest bearing assets. (1) <br>Holding money forgoes the option of holding interest bearing assets, (1) <br>and the cost of doing so is the nominal interest rate. (1)",
    "[14.12 (c)] Verbal elaboration: The purchase of government bonds <u>increases money supply</u> (1) <br>resulting in <u>a drop in the interest rate</u>. (1) <br><u>Investment / consumption expenditure increases</u> as the cost of borrowing decreases (1) <br>and <u>aggregate demand increases</u>. (1) <br>In the short run, the <u>output and price level increases</u>. (1) <br><br>Indicate on the diagram: AD curve shifts to the right (1) <br>Higher price level (1) <br>Higher output (1)",
    "[14.7 (b)] Advantages: An increase in money supply would lower interest rates, lowering the cost of borrowing and thus raise investment and consumption, <u>leading to an increase in aggregate demand and real output in the short run</u>. Given idle resources in the economy, more labour (and/or capital) would be used to produce bigger output, <u>implying a decrease in unemployment</u>. (1) <br>Contractionary fiscal policy would decrease government consumption expenditure and levy higher taxes. Hence decreasing aggregate demand and <u>decreasing GDP and employment in the short run</u>. (1) <br><br>Disadvantages: Expansionary monetary policy would increase money supply, and interest rates would be lowered, decreasing the cost of borrowing and increasing consumption and investment. The resulting <u>increase in aggregate demand</u> would <u>increase the price level</u>. (1) <br>Contractionary fiscal policy would <u>decrease aggregate demand</u> by decreasing government consumption expenditure and levying higher taxes. This results in <u>downward pressure on the price level</u>. Hence, it would not contribute to inflation. (1)",
    "[18.7 (b)] MV = PY, where M: money supply, V: velocity of circulation of money, P: price level and Y: output (1) <br>In the long run, <u>assume V and Y are both constant</u>. (1) <br>Then when M increases/(decreases), it would <u>lead to</u> P increasing/(decreasing) by the same proportion. (2) <br><br>MV = PY, where M: money supply, V: velocity of circulation of money, P: price level and Y: output (1) <br>In the short run, <u>assume V is constant</u>. (1) <br>Then when the <u>percentage increase/(decrease) in M is higher than that in Y</u>, it would <u>lead to</u> an increase/(decrease) in P as well. (2)",
    "[19.8 (a)(i)] Yes. (1) <br>When Country B has the <u>same resource</u> as Country A, the output of cars would be 200 units which is <u>higher than</u> that of country A. (1)",
    "[17.7 (a)(i)] Uncertain. (1) <br>Without knowing the total amount of resources of both countries, the <u>productivity (output per unit of resource)</u> for food and computers <u>cannot be determined</u>. (1)",
    "[19.8 (a)(ii)] Let T be a unit of toys and C be a unit of cars. <br>The opportunity cost of producing 1C in Country A= 1T (1) <br>The opportunity cost of producing 1C in Country B= 0.6T (1) <br>Yes, Country B has a comparative advantage in producing cars as Country B has a lower opportunity cost in producing cars (0.6T < 1T). (1)",
    "[18.8 (b)] If each country <u>specialises</u> in producing the good in which the country has a <u>lower opportunity cost</u> in producing, (1) <br>then <u>total world output would increase</u>. (1) <br>Japan would export toys, as it has a <u>lower cost</u> of producing toys than China. (1)",
    "[21.9 (b)] Illustrate in the figure: <br>Correct position of the quota (QA) (1) <br>Rightward shift of demand curve (1) <br>A new kinked supply curve (S with quota) (1) <br>Correct position of the final equilibrium point (EA) (1)",
    "[14.11 (a)] The Japanese Yen <u>depreciated</u> against the Hong Kong dollar. (1) <br>As the price of Japanese automobiles does not change, the automobiles <u>become cheaper in terms of HKD</u> and Hong Kong importers will buy more Japanese automobiles. (1) <br>The <u>demand</u> for Japanese automobiles by HK people increases. (1) <br>Quantity transacted increases. (1) <br>Therefore, the total export value of Japanese automobiles increases. <br>Indicate on the diagram: <br>Demand curve shifts to the right (1) <br>A higher quantity transacted (1) <br>Gain in total value (1)",
    "[19.11 (c)] Because of the <u>linked exchange rate system</u>, (1) <br>RMB <u>depreciates</u> against HKD accordingly (1) <br>thus lowering fares <u>in terms of HKD</u>. (1) <br>If the demand is <u>elastic</u>, (1) <br>the percentage drop in price will be <u>smaller</u> than the percentage rise in quantity. (1) <br>Total ticket revenue will therefore <u>increase<u/>. (1) <br>Indicate on the diagram: <br>correct position of gain and loss (1) <br>gain > loss (1)",
    "[13.6 (b)] No, (1) <br>because the BOP balance is –$10 million, (1) <br>which implies a BOP deficit. (1)",
    "[15.12 (a)] A drop in the <u>export of services</u> to mainland tourists (1) <br>would reduce HK’s <u>current account</u> surplus (or enlarge its deficit). (1)",
    "[17.12 (c)] Invisible trade would improve. (1) <br>The increase in cost of travel would result in a fall in the number of British citizens visiting the EU and hence the <u>import of services</u>. (1) <br>Unilateral transfer (secondary income) would worsen. (1) <br>With fewer workers working in the EU, there would be <u>a drop in their remittance</u> back to Britain. (1)",
    "[18.11] Balance of payments would be <u>worsened</u>. (1) <br><u>Export of goods</u> would fall because of the embargo. (1) <br><u>Export of services</u> would also fall as fewer tourists would want to visit Country Z because of the threat of war. (1) <br>Foreign investors would withdraw their investments in Country Z, so <u>capital outflow may increase</u>. (1)"
  ]